---
azs:
- name: default

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: common
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: master
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: worker
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: 10240
  disk_size: 10_240
- name: 5120
  disk_size: 5_120

networks:
- name: default
  type: manual
  subnets:
  - range: 10.240.0.0/16
    gateway: 10.240.0.1
    azs: [default]
    dns: [8.8.8.8]
    static : [10.240.0.2-10.240.0.10]

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: default
  vm_type: default
  network: default
