name: kubo-bosh-lite

features:
  use_dns_addresses: true

releases:
- name: kubo
  version: 0.10.0
  url: https://github.com/cloudfoundry-incubator/kubo-release/releases/download/v0.10.0/kubo-release-0.10.0.tgz
- name: kubo-etcd
  version: '6'
  url: https://github.com/pivotal-cf-experimental/kubo-etcd/releases/download/v6/kubo-etcd.6.tgz
- name: docker
  version: 30.1.4
  url: https://github.com/cloudfoundry-community/docker-boshrelease/releases/download/v30.1.4/docker-30.1.4.tgz
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: '3468.21'
instance_groups:
- name: master
  instances: 1
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-password: ((kubo-admin-password))
      admin-username: admin
      authorization-mode: rbac
      backend_port: 8443
      kube-proxy-password: "((kube-proxy-password))"
      kube-scheduler-password: "((kube-scheduler-password))"
      kubelet-password: "((kubelet-password))"
      port: 8443
      route-sync-password: "((route-sync-password))"
      tls:
        kubernetes:
          ca: "((tls-kubernetes.ca))"
          certificate: "((tls-kubernetes.certificate))"
          private_key: "((tls-kubernetes.private_key))"
  - name: kubernetes-controller-manager
    release: kubo
    properties:
      tls:
        kubernetes: "((tls-kubernetes))"
  - name: kubernetes-scheduler
    release: kubo
    properties:
      api-token: "((kube-scheduler-password))"
  - name: kubernetes-system-specs
    release: kubo
    properties:
      admin-password: ((kubo-admin-password))
      admin-username: admin
      api-token: "((kubelet-password))"
      authorization-mode: rbac
      tls:
        kubernetes: "((tls-kubernetes))"
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        delete_data_dir_on_stop: false
        peer_require_ssl: false
        require_ssl: false
  vm_type: master
  stemcell: trusty
  azs:
  - default
  networks:
  - name: &network-name default
    static_ips: [((kubernetes_master_host))]
- name: worker
  instances: 3
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      bip: 172.17.0.1/24
      default_ulimits:
      - nofile=65536
      env: {}
      flannel: true
      ip_masq: false
      iptables: false
      log_level: error
      storage_driver: overlay
      store_dir: "/var/vcap/store"
      tls_cacert: "((tls-docker.ca))"
      tls_cert: "((tls-docker.certificate))"
      tls_key: "((tls-docker.private_key))"
  - name: kubelet
    release: kubo
    properties:
      api-token: "((kubelet-password))"
      tls:
        kubelet: "((tls-kubelet))"
        kubernetes: "((tls-kubernetes))"
  - name: kubernetes-proxy
    release: kubo
    properties:
      api-token: "((kube-proxy-password))"
      tls:
        kubernetes: "((tls-kubernetes))"
  vm_type: worker
  stemcell: trusty
  persistent_disk_type: '10240'
  azs:
  - default
  networks:
  - name: *network-name
update:
  canaries: 1
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000
  max_in_flight: 1
  serial: true
variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kube-proxy-password
  type: password
- name: kube-scheduler-password
  type: password
- name: route-sync-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    common_name: ca
    is_ca: true
- name: tls-kubelet
  type: certificate
  options:
    alternative_names: []
    ca: kubo_ca
    common_name: kubelet.kubo.internal
    organization: system:nodes
- name: tls-kubernetes
  type: certificate
  options:
    alternative_names:
    - ((kubernetes_master_host))
    - 10.100.200.1
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - master.kubo
    ca: kubo_ca
    common_name: ((kubernetes_master_host))
    organization: system:masters
- name: tls-docker
  type: certificate
  options:
    ca: kubo_ca
    common_name: docker.kubo.internal



